name: YML & Editorial Checkers
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  yml_editorial_checkers:
    runs-on: ubuntu-latest
    container:
      image: vulnerabilityhistory/curations:latest
      volumes:
        - /:/
    steps:
    - run: pwd
    - uses: actions/checkout@v3
      with:
       fetch-depth: 1
    - name: Run YML and editorial checkers
      run: rspec
